name: PPO
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=6.15.0
  - ipython=8.4.0
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - matplotlib-inline=0.1.6
  - pip=23.0.1
  - python=3.8.16
  - pip:
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - matplotlib==3.7.1
      - tqdm==4.65.0
